services:
  - type: web
    name: mathlens-ia-server
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:${PORT} main:app
    autoDeploy: true
